# -*- coding: utf-8 -*-
"""kadai_015

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UvcPhKUEwMiQl9O8N4quq-fF7mMHJMRx
"""

class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def printinfo(self):
    print(self.name)
    print(self.age)

man1 = Human("あああ", 85)
man1.printinfo()